#!/bin/sh
rendertext="True"
prefix="/tmp/buienradar"
screen_width="1920"
screen_height="1080"
height=512
width=550
extension="png"
delay="0.7"

[ -n "$1" ] && mode="$1" || mode="1h"

timestamp=$(TZ=UCT date +%Y%m%d%H%M)
if [ "$mode" = "1h" -o "$mode" = "1" -o "$mode" = "h" ]; then
	map="RadarMapRainNL"
	amount=12
	skip=0
elif [ "$mode" = "3h" -o "$mode" = "3" ]; then
	map="RadarMapRainNL"
	amount=18
	skip=1
elif [ "$mode" = "24h" -o "$mode" = "24" ]; then
	map="RadarMapRain24HourForecastNL"
	amount=24
	skip=0
else
	printf "invalid mode\n"
	exit
fi

URL="https://image.buienradar.nl/2.0/image/sprite/${map}?\
extension=${extension}&width=${width}&height=${height}&renderText=${rendertext}\
&renderBranding=False&renderBackground=True&history=0&forecast=${amount}&skip=${skip}&timestamp=${timestamp}"

rm -rf "${prefix}"
mkdir -p "${prefix}/sub"

wget --no-verbose "$URL" -O "${prefix}/radar.${extension}"
magick convert "$prefix/radar.png" -crop "${width}x${height}" "${prefix}/sub/radar%d.${extension}" 
xpos="$(( (screen_width-width)/2 ))"
ypos="$(( (screen_height-height)/2 ))"
sxiv -s f -N "buienradar" -b -S "$delay" -g "${width}x${height}+${xpos}+${ypos}" $(find /tmp/buienradar/sub -maxdepth 1 -name "*.${extension}" | sort -V)
