#!/bin/sh
rendertext="True"
prefix="/tmp/buienradar"
resolution=$(xrandr | grep '*' | head -1 | awk '{print $1}')
screen_width="${resolution%x*}"
screen_height="${resolution#*x}"
height=512
width=550
extension="png"

[ -n "$1" ] && mode="$1" || mode="1h"

timestamp=$(TZ=UCT date +%Y%m%d%H%M)
if [ "$mode" = "1h" -o "$mode" = "1" -o "$mode" = "h" ]; then
	amount=12
	map="RadarMapRainNL"
	skip=0
elif [ "$mode" = "3h" -o "$mode" = "3" ]; then
	amount=18
	map="RadarMapRainNL"
	skip=1
elif [ "$mode" = "24h" -o "$mode" = "24" ]; then
	amount=24
	skip=0
	map="RadarMapRain24HourForecastNL"
elif [ "$mode" = "48h" -o "$mode" = "48" ]; then
	amount=24
	map="RadarMapRain24HourForecastNL"
	skip=0
else
	printf "invalid mode\n"
	exit
fi

URL="https://image.buienradar.nl/2.0/image/sprite/${map}?\
	extension=${extension}&width=${width}&height=${height}&renderText=${rendertext}\
	&renderBranding=False&renderBackground=True&history=0&forecast=${amount}&skip=${skip}&timestamp=${timestamp}"

rm -rf "${prefix}"
mkdir -p "${prefix}/sub"

wget "$URL" -O "${prefix}/radar.${extension}" &>/dev/null
convert -crop "${width}x${height}" "$prefix/radar.png" "${prefix}/sub/radar%d.${extension}" 
xpos="$(( (screen_width-width)/2 ))"
ypos="$(( (screen_height-height)/2 ))"
sxiv -s f -N "buienradar" -b -S "0.5" -g "${width}x${height}+${xpos}+${ypos}" $(find /tmp/buienradar/sub -maxdepth 1 -name "*.${extension}" | sort -V)
